config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'contact', to: 'home#contact'

  namespace :admin do
      delete '/messages/:id', to: 'messages#destroy'
      get '/', to: 'messages#index', as: 'messages'
			resources :slides, only: [:index, :new, :edit, :create, :destroy, :update]
  end
  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
    has_secure_password
end

app/models/message.rb
class Message < ActiveRecord::Base
    # Last messages first
    scope :sorted, -> { order('created_at DESC') }
end

app/models/order.rb
class Order < ActiveRecord::Base
	mount_uploader :photo, OrderPhotoUploader
	serialize :photo, JSON
end

app/models/slide.rb
class Slide < ActiveRecord::Base
	mount_uploader :photo, SlidePhotoUploader
	serialize :photo, JSON
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
    layout 'admin'
  def index
      @messages = Message.sorted
  end

  def destroy
      @message = Message.find(params[:id])
      respond_to do |format|
	  if @message.delete
	      format.html { render 'index' }
	      format.json { render :json => {:message_id => @message.id, :error => ''},
		     status: 200 }
	  else
	      flash.now[:error] = @message.error
	      format.html { render 'index' }
	      format.json { render :json => {:error => ''},
		     status: 500 }
	  end
      end
  end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
	layout 'admin'
	def new
		@slide = Slide.new
	end

	def index
		@slides = Slide.all		
	end

	def edit
		@slide = Slide.find(params[:id])
	end

	def create
		@slide = Slide.new(slider_params)
		if @slide.save
			flash[:notice] = 'Слайд добавлен'
			redirect_to admin_slides_path
		else
			flash.now[:error] = 'Не удалось добавить слайд'
		end
	end

	def update
		@slide = Slide.find(params[:id])
		if @slide.update_attributes(slider_params)
			flash[:notice] = 'Слайд изменён'
			redirect_to admin_slides_path
		else
			flash.now[:error] = 'Не удалось изменить слайд'
		end
	end

	def destroy
		@slide = Slide.find(params[:id])
		if @slide.delete
			flash[:notice] = 'Слайд был удалён'
		else
			flash[:error] = 'Не удалось удалить слайд'
		end
		redirect_to admin_slides_path
	end

	private

	def slider_params
		params.require(:slide).permit(:photo, :name, :description)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/admin/messages/index.html.erb
<div class="messages">
    <div class="summary"> Всего: <%= @message ? @messages.size : 0 %>  </div>
    <table>
	<thead>
	    <th>Имя</th>
	    <th>Название компании</th>
	    <th>Почта</th>
	    <th>Телефон</th>
	    <th>Вариант заказа</th>
	    <th>Комментарий</th>
	    <th></th>
	</thead>
	<tbody>
	    <% @messages.each do |message| %>
		<tr data-message-id="<%= message.id %>" >
		    <td><%= message.name %></td>
		    <td><%= message.company_name %></td>
		    <td><%= message.email %></td>
		    <td><%= message.telephone %></td>
		    <td><%= message.type_of_order %></td>
		    <td><%= message.comment %></td>
		    <td class="message__delete">x</td>
		</tr>
	    <% end %>
	</tbody>
    </table>
</div>

app/views/admin/slides/_form.html.erb
<div class="slide-view">
	<div class="slide-form">
		<span class='slide-label'>Заголовок слайда</span>
		<%= f.text_field :name %>
		<span class='slide-label'>Описание слайда</span>
		<%= f.text_area :description %>
		<span class='slide-label'>Изображение</span>
		<%= f.file_field :photo %>
		<%= f.submit 'Сохранить'%>
	</div>
		<% if f.object.photo.url %>
			<img src="<%= f.object.photo.url %>" />
		<% end %>
</div>

app/views/admin/slides/edit.html.erb
<%= form_for @slide,  url: url_for(controller: 'slides', action: 'update') do |f| %>
<%= render partial: 'form', locals: {:f => f}%>
<% end %>

app/views/admin/slides/index.html.erb
<%= link_to('Добавить слайд', new_admin_slide_path, class: 'slide-btn') %>
<div class="slides">
<% @slides.each do |slide| %>
	<div class="slide">
		<div class="slide__name"><%= slide.name %></div>		
		<div class="slide__description"><%= slide.description %></div>
		<img src="<%= slide.photo.url %>" />
		<%= link_to 'Изменить что-то в слайде', edit_admin_slide_path(slide), class: 'slide-btn' %>
		<%= button_to 'Удалить слайд', admin_slide_path(slide), method: :delete, class: 'slide-btn' %>
	</div>
<% end %>
</div>

app/views/admin/slides/new.html.erb
<%= form_for @slide,  url: admin_slides_path(@slide) do |f| %>
<%= render partial: 'form', locals: {:f => f}%>
<% end %>

app/views/home/_footer.html.erb
<footer>
	<div class="footer-start">
		<div class="footer-menu">
			<div class="menu">
				<span>О нас</span>
				<ul>
					<li><a href="#">Кто мы</a></li>
					<li><a href="#">Наши работы</a></li>
					<li><a href="#">Отзывы</a></li>
				</ul>
			</div>
			<div class="menu">
				<span>Услуги</span>
				<ul>
					<li><a href="#">Сайт-визитка</a></li>
					<li><a href="#">Личный Блог</a></li>
					<li><a href="#">Каталог товаров</a></li>
					<li><a href="#">Интернет магазин</a></li>
				</ul>
			</div>
			<div class="menu">
				<span>Связаться</span>
				<ul>
					<li><a href="#">Почта</a></li>
				</ul>
			</div>
		</div>
		<!--
		<div class="message">
		<form>
		<input class="message-field"  type="text" placeholder="Sign up for our newsletter" id="newsletter" name="email" size="40" maxlength="100" value="">
		<input class ="btn btn-send" type="submit" name="submit" value="Отправить">
		</form>
		</div>
		-->
	</div>

	<div class="footer-end">
		<div class="footer-end-end">
			<div class="copy">
				© 2017 Martin Web Studio. All Rights Reserved.
			</div>
			<div class="links">
				<a href="#"><i class="fa fa-instagram fa-2x" aria-hidden=true></i></a>
				<a href="#"><i class="fa fa-vk fa-2x" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i></a>
			</div>
		</div>
	</div>  
</footer>

app/views/home/_message_us.html.erb
<div class="message">
	<div class="message__form">
	<span class="message__header">Напишите нам о себе</span>
		<input type="text" name="name" placeholder="Ваше имя" />
		<input type="text" name="company_name" placeholder="Название вашей компании" />
		<input type="email" name="email" placeholder="Ваша электронная почта" />
		<input type="text" name="telephone" placeholder="Номер телефона" />
		<textarea name="comment" placeholder="Ваше сообщение"></textarea>
		<button >Написать</button>
	</div>
</div>

app/views/home/_our_orders.html.erb
<section class="our-orders">
	<div class="our-order">
		<div class="imag">
			<img class="screen" src="https://contentmaximiser.com/wp-content/uploads/2015/08/sales-landing-page.jpg">
		</div>
		<div class="info"> 
			<div class="description">
				<h2>Langing page</h2>
				<h3>Страница для вашего бизнеса, через которую люди узнают о вас.</h3>
			</div>
			<div>
				<ul>
					<li>Разработка собственного дизайна. </li>
					<li>Консоль для управления сайтом. </li>
					<li>Счётчик посещений.</li>
					<li>Разработка ТЗ в соответствии с требованиями.</li>
				</ul>
			</div>
		</div> 
	</div>
	<div class="our-order">
		<div class="imag">
			<img class="screen" src="https://contentmaximiser.com/wp-content/uploads/2015/08/sales-landing-page.jpg">
		</div>
		<div class="info">
			<div class="description">
				<h2>Блог</h2>
				<h3>Ваш персональный сайт, где вы вольны делиться с миром лучшим, что у вас есть.</h3>
			</div>
			<div>
				<ul>
					<li>Разработка собственного дизайна. </li>
					<li>Консоль для управления сайтом. </li>
					<li>Счётчик посещений.</li>
					<li>Разработка ТЗ в соответствии с требованиями.</li>
				</ul>
			</div>
		</div>
	</div> 
	<div class="our-order">
		<div class="imag">
			<img class="screen" src="https://contentmaximiser.com/wp-content/uploads/2015/08/sales-landing-page.jpg">
		</div>
		<div  class="info">
			<div class="description">
				<h2>Магазин/каталог</h2>
				<h3>Магазин для просмотра и заказа ваших товаров и услуг.</h3>
			</div>
			<div>
				<ul>
					<li>Разработка собственного дизайна. </li>
					<li>Консоль для управления сайтом. </li>
					<li>Счётчик посещений.</li>
					<li>Разработка ТЗ в соответствии с требованиями.</li>
				</ul>
			</div>
		</div>
	</div>
</section>
</div>

app/views/home/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="carousel-item carousel-back-1 active">
			<!--  <img class="first-slide" src="../img/1-slide.jpg" alt="First slide"> -->
			<div class="container">
				<div class="carousel-caption d-md-block ">
					<h1>Практичность</h1>
					<p>Мы разрабатываем уникальный, практичный продукт - сайт, с помощью которого вы сможете выполнять поставленные вами цели. Наш основной принцип в разработке - ничего лишнего и всё необходимое.</p>
				</div>
			</div>
		</div>
		<div class="carousel-item carousel-back-2">
			<!--  <img class="second-slide" src="../img/2-slide.jpg" alt="Second slide"> -->
			<div class="container">
				<div class="carousel-caption  d-md-block">
					<h1>Эстетичность</h1>
					<p>Мы следим за современными течениями в области web-индустрии и вкладываем лучшее из неё в свои проекты. Эргономичность, простота и элегантность - вот наши требования к внешнему виду каждого сайта.</p>
				</div>
			</div>
		</div>
		<div class="carousel-item carousel-back-3">
			<!-- <img class="third-slide" src="../img/3-slide.jpg" alt="Third slide"> -->
			<div class="container">
				<div class="carousel-caption  d-md-block ">
					<h1>Поддержка</h1>
					<p>Мы не оставляем наших клиентов после завершения и запуска проекта. Так как потенциально могут возникнуть проблемы или вопросы, мы не теряем контакт.</p>
				</div>
			</div>
		</div>
	</div>
	<a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
		</a>
</div>

app/views/home/contact.html.erb
<div id="main">
    <div style="margin-top:28px">dfdsf</div>


</div>

app/views/home/index.html.erb
<%= render :partial => 'slider' %>
<%= render :partial => 'our_orders' %>
<%= render :partial => 'message_us' %>
<%= render :partial => 'footer' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Martin Console</title>
  <%= stylesheet_link_tag    'admin/admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul>
		<li><%= link_to('Сообщения', admin_messages_path) %></li>
		<li><%= link_to('Слайды', admin_slides_path) %></li>
	</ul>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Martin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Dev-Studio</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
       <!--  <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">О нас<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Портфолио</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Заказать</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Контакты</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Поиск по сайту">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form> -->
      </div>
    </nav>
</header>
<%= yield %>

</body>
</html>